# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TechLab
email: info@techlab.lv
description: > # this means to ignore newlines until "baseurl:"
  TechLab - community for technology entrepreneurs, scientists, coders and engineers.. a place where new startups are born. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.techlab.lv" # the base hostname & protocol for your site
#twitter_username: xx
facebook_address: https://www.facebook.com/techlablatvia/
#github_username:  xx

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
